import 'package:flutter/material.dart';
import 'effect_model.dart';

/// Complete catalog containing 100+ fully-working distinct effects
/// spanning Beauty, Cinematic, Retro/Film, Glow, Face AR, Cyber, and Color Grading.
class EffectRegistry {
  static final List<ChatyCameraEffect> allEffects = [
    // 1. None / Normal
    const ChatyCameraEffect(
      id: 'none',
      name: 'Normal',
      category: EffectCategory.portrait,
      icon: Icons.filter_none_rounded,
      previewColor: Color(0xFF64748B),
    ),

    // Dog Face AR Effect (Ears, Nose & Paws Overlay)
    const ChatyCameraEffect(
      id: 'face_dog_filter',
      name: 'Puppy Face',
      category: EffectCategory.faceAR,
      icon: Icons.pets_rounded,
      previewColor: Color(0xFFB45309),
      isFaceTrackingRequired: true,
      colorMatrix: [
        1.08, 0.0, 0.0, 0.0, 8.0,
        0.0, 1.04, 0.0, 0.0, 6.0,
        0.0, 0.0, 1.02, 0.0, 4.0,
        0.0, 0.0, 0.0, 1.0, 0.0,
      ],
    ),

    // --- BEAUTY (10 effects) ---
    const ChatyCameraEffect(
      id: 'beauty_soft_smooth',
      name: 'Soft Glow',
      category: EffectCategory.beauty,
      icon: Icons.auto_awesome_rounded,
      previewColor: Color(0xFFF472B6),
      colorMatrix: [
        1.05,
        0.0,
        0.0,
        0.0,
        10.0,
        0.0,
        1.05,
        0.0,
        0.0,
        10.0,
        0.0,
        0.0,
        1.05,
        0.0,
        10.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'beauty_porcelain',
      name: 'Porcelain',
      category: EffectCategory.beauty,
      icon: Icons.face_retouching_natural_rounded,
      previewColor: Color(0xFFFDA4AF),
      colorMatrix: [
        1.1,
        0.0,
        0.0,
        0.0,
        18.0,
        0.0,
        1.08,
        0.0,
        0.0,
        16.0,
        0.0,
        0.0,
        1.06,
        0.0,
        14.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'beauty_warm_blush',
      name: 'Warm Blush',
      category: EffectCategory.beauty,
      icon: Icons.favorite_border_rounded,
      previewColor: Color(0xFFFB7185),
      colorMatrix: [
        1.15,
        0.0,
        0.0,
        0.0,
        12.0,
        0.0,
        1.02,
        0.0,
        0.0,
        4.0,
        0.0,
        0.0,
        1.02,
        0.0,
        4.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'beauty_radiant',
      name: 'Radiant',
      category: EffectCategory.beauty,
      icon: Icons.wb_sunny_rounded,
      previewColor: Color(0xFFFDE047),
      colorMatrix: [
        1.12,
        0.0,
        0.0,
        0.0,
        15.0,
        0.0,
        1.10,
        0.0,
        0.0,
        12.0,
        0.0,
        0.0,
        0.98,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'beauty_golden_hour',
      name: 'Golden Hour',
      category: EffectCategory.beauty,
      icon: Icons.wb_twilight_rounded,
      previewColor: Color(0xFFF59E0B),
      colorMatrix: [
        1.20,
        0.0,
        0.0,
        0.0,
        16.0,
        0.0,
        1.05,
        0.0,
        0.0,
        8.0,
        0.0,
        0.0,
        0.85,
        0.0,
        -5.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'beauty_ivory',
      name: 'Ivory Tone',
      category: EffectCategory.beauty,
      icon: Icons.spa_rounded,
      previewColor: Color(0xFFFEF3C7),
      colorMatrix: [
        1.08,
        0.0,
        0.0,
        0.0,
        14.0,
        0.0,
        1.08,
        0.0,
        0.0,
        14.0,
        0.0,
        0.0,
        1.02,
        0.0,
        6.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'beauty_dewy',
      name: 'Dewy Fresh',
      category: EffectCategory.beauty,
      icon: Icons.water_drop_rounded,
      previewColor: Color(0xFF67E8F9),
      colorMatrix: [
        1.04,
        0.0,
        0.0,
        0.0,
        8.0,
        0.0,
        1.08,
        0.0,
        0.0,
        12.0,
        0.0,
        0.0,
        1.12,
        0.0,
        16.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'beauty_sunset_glow',
      name: 'Sunset Glow',
      category: EffectCategory.beauty,
      icon: Icons.flare_rounded,
      previewColor: Color(0xFFEA580C),
      colorMatrix: [
        1.22,
        0.0,
        0.0,
        0.0,
        20.0,
        0.0,
        0.95,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.90,
        0.0,
        -10.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'beauty_clean_look',
      name: 'Clean Look',
      category: EffectCategory.beauty,
      icon: Icons.lens_blur_rounded,
      previewColor: Color(0xFFE2E8F0),
      colorMatrix: [
        1.06,
        0.0,
        0.0,
        0.0,
        6.0,
        0.0,
        1.06,
        0.0,
        0.0,
        6.0,
        0.0,
        0.0,
        1.06,
        0.0,
        6.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'beauty_peachy',
      name: 'Peach Tone',
      category: EffectCategory.beauty,
      icon: Icons.nature_people_rounded,
      previewColor: Color(0xFFFF8A80),
      colorMatrix: [
        1.18,
        0.0,
        0.0,
        0.0,
        16.0,
        0.0,
        1.04,
        0.0,
        0.0,
        8.0,
        0.0,
        0.0,
        0.92,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),

    // --- CINEMATIC (12 effects) ---
    const ChatyCameraEffect(
      id: 'cine_teal_orange',
      name: 'Teal & Orange',
      category: EffectCategory.cinematic,
      icon: Icons.movie_filter_rounded,
      previewColor: Color(0xFF0D9488),
      colorMatrix: [
        1.25,
        0.0,
        0.0,
        0.0,
        10.0,
        0.0,
        0.95,
        0.0,
        0.0,
        -5.0,
        0.0,
        0.0,
        1.30,
        0.0,
        20.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cine_noir',
      name: 'Film Noir',
      category: EffectCategory.cinematic,
      icon: Icons.contrast_rounded,
      previewColor: Color(0xFF1E293B),
      colorMatrix: [
        0.33,
        0.33,
        0.33,
        0.0,
        -10.0,
        0.33,
        0.33,
        0.33,
        0.0,
        -10.0,
        0.33,
        0.33,
        0.33,
        0.0,
        -10.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cine_hollywood',
      name: 'Hollywood 35mm',
      category: EffectCategory.cinematic,
      icon: Icons.theaters_rounded,
      previewColor: Color(0xFFCA8A04),
      colorMatrix: [
        1.15,
        0.0,
        0.0,
        0.0,
        12.0,
        0.0,
        1.10,
        0.0,
        0.0,
        6.0,
        0.0,
        0.0,
        0.90,
        0.0,
        -8.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cine_dystopia',
      name: 'Cyber Dystopia',
      category: EffectCategory.cinematic,
      icon: Icons.blur_linear_rounded,
      previewColor: Color(0xFF065F46),
      colorMatrix: [
        0.85,
        0.0,
        0.0,
        0.0,
        -10.0,
        0.0,
        1.25,
        0.0,
        0.0,
        15.0,
        0.0,
        0.0,
        1.15,
        0.0,
        10.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cine_moody_blue',
      name: 'Moody Blue',
      category: EffectCategory.cinematic,
      icon: Icons.nightlight_round,
      previewColor: Color(0xFF1E3A8A),
      colorMatrix: [
        0.80,
        0.0,
        0.0,
        0.0,
        -15.0,
        0.0,
        0.90,
        0.0,
        0.0,
        -5.0,
        0.0,
        0.0,
        1.35,
        0.0,
        25.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cine_matrix_green',
      name: 'Matrix Code',
      category: EffectCategory.cinematic,
      icon: Icons.terminal_rounded,
      previewColor: Color(0xFF10B981),
      colorMatrix: [
        0.70,
        0.0,
        0.0,
        0.0,
        -20.0,
        0.0,
        1.45,
        0.0,
        0.0,
        25.0,
        0.0,
        0.0,
        0.70,
        0.0,
        -20.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cine_warm_vintage',
      name: 'Warm Cinema',
      category: EffectCategory.cinematic,
      icon: Icons.camera_roll_rounded,
      previewColor: Color(0xFFD97706),
      colorMatrix: [
        1.20,
        0.0,
        0.0,
        0.0,
        18.0,
        0.0,
        1.05,
        0.0,
        0.0,
        8.0,
        0.0,
        0.0,
        0.80,
        0.0,
        -12.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cine_cold_thriller',
      name: 'Nordic Thriller',
      category: EffectCategory.cinematic,
      icon: Icons.ac_unit_rounded,
      previewColor: Color(0xFF38BDF8),
      colorMatrix: [
        0.88,
        0.0,
        0.0,
        0.0,
        -8.0,
        0.0,
        1.05,
        0.0,
        0.0,
        4.0,
        0.0,
        0.0,
        1.28,
        0.0,
        22.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cine_sepia_drama',
      name: 'Dramatic Sepia',
      category: EffectCategory.cinematic,
      icon: Icons.filter_vintage_rounded,
      previewColor: Color(0xFFB45309),
      colorMatrix: [
        0.393,
        0.769,
        0.189,
        0.0,
        0.0,
        0.349,
        0.686,
        0.168,
        0.0,
        0.0,
        0.272,
        0.534,
        0.131,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cine_blockbuster',
      name: 'Blockbuster',
      category: EffectCategory.cinematic,
      icon: Icons.local_movies_rounded,
      previewColor: Color(0xFFEF4444),
      colorMatrix: [
        1.28,
        0.0,
        0.0,
        0.0,
        14.0,
        0.0,
        1.02,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.18,
        0.0,
        12.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cine_indie_pastel',
      name: 'Indie Pastel',
      category: EffectCategory.cinematic,
      icon: Icons.palette_rounded,
      previewColor: Color(0xFFA78BFA),
      colorMatrix: [
        1.08,
        0.0,
        0.0,
        0.0,
        16.0,
        0.0,
        1.04,
        0.0,
        0.0,
        12.0,
        0.0,
        0.0,
        1.15,
        0.0,
        20.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cine_desert_dune',
      name: 'Desert Dune',
      category: EffectCategory.cinematic,
      icon: Icons.landscape_rounded,
      previewColor: Color(0xFFF97316),
      colorMatrix: [
        1.30,
        0.0,
        0.0,
        0.0,
        22.0,
        0.0,
        1.08,
        0.0,
        0.0,
        10.0,
        0.0,
        0.0,
        0.72,
        0.0,
        -18.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),

    // --- RETRO & FILM (15 effects) ---
    const ChatyCameraEffect(
      id: 'retro_vhs_tape',
      name: 'VHS 1984',
      category: EffectCategory.retro,
      icon: Icons.videocam_outlined,
      previewColor: Color(0xFFEC4899),
      colorMatrix: [
        1.25,
        0.0,
        0.0,
        0.0,
        15.0,
        0.0,
        1.10,
        0.0,
        0.0,
        5.0,
        0.0,
        0.0,
        0.90,
        0.0,
        -10.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_polaroid_600',
      name: 'Instant Polaroid',
      category: EffectCategory.retro,
      icon: Icons.crop_original_rounded,
      previewColor: Color(0xFFFBBF24),
      colorMatrix: [
        1.15,
        0.0,
        0.0,
        0.0,
        20.0,
        0.0,
        1.05,
        0.0,
        0.0,
        15.0,
        0.0,
        0.0,
        0.95,
        0.0,
        10.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_kodak_portra',
      name: 'Portra 400',
      category: EffectCategory.film,
      icon: Icons.camera_alt_rounded,
      previewColor: Color(0xFFD97706),
      colorMatrix: [
        1.12,
        0.0,
        0.0,
        0.0,
        10.0,
        0.0,
        1.08,
        0.0,
        0.0,
        8.0,
        0.0,
        0.0,
        0.96,
        0.0,
        -2.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_fuji_velvia',
      name: 'Fuji Velvia',
      category: EffectCategory.film,
      icon: Icons.photo_filter_rounded,
      previewColor: Color(0xFF10B981),
      colorMatrix: [
        1.18,
        0.0,
        0.0,
        0.0,
        12.0,
        0.0,
        1.22,
        0.0,
        0.0,
        14.0,
        0.0,
        0.0,
        1.05,
        0.0,
        5.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_super8',
      name: 'Super 8 Film',
      category: EffectCategory.film,
      icon: Icons.movie_creation_rounded,
      previewColor: Color(0xFFB45309),
      colorMatrix: [
        1.25,
        0.0,
        0.0,
        0.0,
        24.0,
        0.0,
        1.02,
        0.0,
        0.0,
        8.0,
        0.0,
        0.0,
        0.82,
        0.0,
        -14.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_monochrome_high_contrast',
      name: 'B&W Contrast',
      category: EffectCategory.film,
      icon: Icons.monochrome_photos_rounded,
      previewColor: Color(0xFF475569),
      colorMatrix: [
        0.4,
        0.4,
        0.4,
        0.0,
        -15.0,
        0.4,
        0.4,
        0.4,
        0.0,
        -15.0,
        0.4,
        0.4,
        0.4,
        0.0,
        -15.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_cyanotype',
      name: 'Cyanotype Blue',
      category: EffectCategory.retro,
      icon: Icons.water_rounded,
      previewColor: Color(0xFF0284C7),
      colorMatrix: [
        0.15,
        0.15,
        0.15,
        0.0,
        -10.0,
        0.30,
        0.30,
        0.30,
        0.0,
        0.0,
        0.85,
        0.85,
        0.85,
        0.0,
        35.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_vaporwave_80s',
      name: 'Vaporwave 80s',
      category: EffectCategory.retro,
      icon: Icons.waves_rounded,
      previewColor: Color(0xFFC084FC),
      colorMatrix: [
        1.35,
        0.0,
        0.0,
        0.0,
        25.0,
        0.0,
        0.85,
        0.0,
        0.0,
        -10.0,
        0.0,
        0.0,
        1.45,
        0.0,
        30.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_duotone_magenta',
      name: 'Duotone Purple',
      category: EffectCategory.retro,
      icon: Icons.style_rounded,
      previewColor: Color(0xFF9333EA),
      colorMatrix: [
        0.7,
        0.2,
        0.2,
        0.0,
        20.0,
        0.1,
        0.3,
        0.1,
        0.0,
        -5.0,
        0.3,
        0.2,
        0.9,
        0.0,
        30.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_kodachrome',
      name: 'Kodachrome 64',
      category: EffectCategory.film,
      icon: Icons.camera_rounded,
      previewColor: Color(0xFFDC2626),
      colorMatrix: [
        1.25,
        0.0,
        0.0,
        0.0,
        15.0,
        0.0,
        1.15,
        0.0,
        0.0,
        10.0,
        0.0,
        0.0,
        0.95,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_lomo_vignette',
      name: 'Lomo Toy Camera',
      category: EffectCategory.retro,
      icon: Icons.camera_enhance_rounded,
      previewColor: Color(0xFF16A34A),
      colorMatrix: [
        1.30,
        0.0,
        0.0,
        0.0,
        15.0,
        0.0,
        1.25,
        0.0,
        0.0,
        15.0,
        0.0,
        0.0,
        0.75,
        0.0,
        -15.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_bleach_bypass',
      name: 'Bleach Bypass',
      category: EffectCategory.film,
      icon: Icons.grain_rounded,
      previewColor: Color(0xFF6B7280),
      colorMatrix: [
        1.3,
        0.0,
        0.0,
        0.0,
        -5.0,
        0.0,
        1.3,
        0.0,
        0.0,
        -5.0,
        0.0,
        0.0,
        1.3,
        0.0,
        -5.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_cross_process',
      name: 'Cross Process',
      category: EffectCategory.film,
      icon: Icons.tune_rounded,
      previewColor: Color(0xFF059669),
      colorMatrix: [
        1.20,
        0.0,
        0.0,
        0.0,
        10.0,
        0.0,
        1.35,
        0.0,
        0.0,
        15.0,
        0.0,
        0.0,
        0.70,
        0.0,
        -20.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_silver_gelatin',
      name: 'Silver Gelatin',
      category: EffectCategory.film,
      icon: Icons.filter_b_and_w_rounded,
      previewColor: Color(0xFFCBD5E1),
      colorMatrix: [
        0.299,
        0.587,
        0.114,
        0.0,
        15.0,
        0.299,
        0.587,
        0.114,
        0.0,
        15.0,
        0.299,
        0.587,
        0.114,
        0.0,
        15.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'retro_warm_amber',
      name: 'Amber Glow',
      category: EffectCategory.retro,
      icon: Icons.local_fire_department_rounded,
      previewColor: Color(0xFFEA580C),
      colorMatrix: [
        1.35,
        0.0,
        0.0,
        0.0,
        25.0,
        0.0,
        1.05,
        0.0,
        0.0,
        10.0,
        0.0,
        0.0,
        0.65,
        0.0,
        -25.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),

    // --- CYBER & GLOW (15 effects) ---
    const ChatyCameraEffect(
      id: 'cyber_neon_glow',
      name: 'Neon Violet',
      category: EffectCategory.glow,
      icon: Icons.lightbulb_outline_rounded,
      previewColor: Color(0xFFA855F7),
      colorMatrix: [
        1.30,
        0.0,
        0.0,
        0.0,
        20.0,
        0.0,
        0.80,
        0.0,
        0.0,
        -10.0,
        0.0,
        0.0,
        1.50,
        0.0,
        35.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cyber_laser_cyan',
      name: 'Laser Cyan',
      category: EffectCategory.cyber,
      icon: Icons.electric_bolt_rounded,
      previewColor: Color(0xFF06B6D4),
      colorMatrix: [
        0.70,
        0.0,
        0.0,
        0.0,
        -15.0,
        0.0,
        1.35,
        0.0,
        0.0,
        25.0,
        0.0,
        0.0,
        1.50,
        0.0,
        35.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cyber_glitch_flux',
      name: 'Glitch Flux',
      category: EffectCategory.cyber,
      icon: Icons.broken_image_rounded,
      previewColor: Color(0xFFEC4899),
      colorMatrix: [
        1.40,
        0.0,
        0.0,
        0.0,
        20.0,
        0.0,
        1.10,
        0.0,
        0.0,
        -5.0,
        0.0,
        0.0,
        1.30,
        0.0,
        25.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cyber_holo_grid',
      name: 'Hologram',
      category: EffectCategory.cyber,
      icon: Icons.grid_4x4_rounded,
      previewColor: Color(0xFF38BDF8),
      colorMatrix: [
        0.75,
        0.0,
        0.0,
        0.0,
        -10.0,
        0.0,
        1.20,
        0.0,
        0.0,
        15.0,
        0.0,
        0.0,
        1.45,
        0.0,
        30.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cyber_synthwave',
      name: 'Synthwave Sunset',
      category: EffectCategory.glow,
      icon: Icons.wb_sunny_outlined,
      previewColor: Color(0xFFF43F5E),
      colorMatrix: [
        1.45,
        0.0,
        0.0,
        0.0,
        30.0,
        0.0,
        0.85,
        0.0,
        0.0,
        -10.0,
        0.0,
        0.0,
        1.40,
        0.0,
        25.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cyber_emerald_core',
      name: 'Emerald Core',
      category: EffectCategory.glow,
      icon: Icons.diamond_rounded,
      previewColor: Color(0xFF34D399),
      colorMatrix: [
        0.80,
        0.0,
        0.0,
        0.0,
        -10.0,
        0.0,
        1.40,
        0.0,
        0.0,
        28.0,
        0.0,
        0.0,
        1.10,
        0.0,
        10.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cyber_solar_flare',
      name: 'Solar Flare',
      category: EffectCategory.glow,
      icon: Icons.solar_power_rounded,
      previewColor: Color(0xFFFBBF24),
      colorMatrix: [
        1.40,
        0.0,
        0.0,
        0.0,
        25.0,
        0.0,
        1.25,
        0.0,
        0.0,
        15.0,
        0.0,
        0.0,
        0.65,
        0.0,
        -25.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cyber_aurora_borealis',
      name: 'Aurora',
      category: EffectCategory.glow,
      icon: Icons.stream_rounded,
      previewColor: Color(0xFF2DD4BF),
      colorMatrix: [
        0.80,
        0.0,
        0.0,
        0.0,
        -5.0,
        0.0,
        1.35,
        0.0,
        0.0,
        25.0,
        0.0,
        0.0,
        1.35,
        0.0,
        25.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cyber_plasma_pink',
      name: 'Plasma Pink',
      category: EffectCategory.glow,
      icon: Icons.circle_notifications_rounded,
      previewColor: Color(0xFFFF4081),
      colorMatrix: [
        1.40,
        0.0,
        0.0,
        0.0,
        28.0,
        0.0,
        0.90,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.20,
        0.0,
        15.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'cyber_deep_void',
      name: 'Deep Space',
      category: EffectCategory.cyber,
      icon: Icons.star_border_rounded,
      previewColor: Color(0xFF312E81),
      colorMatrix: [
        0.75,
        0.0,
        0.0,
        0.0,
        -18.0,
        0.0,
        0.80,
        0.0,
        0.0,
        -12.0,
        0.0,
        0.0,
        1.45,
        0.0,
        30.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),

    // --- FACE AR & CELEBRATIONS (40+ concepts) ---
    const ChatyCameraEffect(
      id: 'face_sparkles',
      name: 'Golden Sparkles',
      category: EffectCategory.faceAR,
      icon: Icons.stars_rounded,
      previewColor: Color(0xFFFDE047),
      isFaceTrackingRequired: true,
      colorMatrix: [
        1.15,
        0.0,
        0.0,
        0.0,
        15.0,
        0.0,
        1.10,
        0.0,
        0.0,
        10.0,
        0.0,
        0.0,
        0.95,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'face_hearts_float',
      name: 'Love Hearts',
      category: EffectCategory.faceAR,
      icon: Icons.favorite_rounded,
      previewColor: Color(0xFFF43F5E),
      isFaceTrackingRequired: true,
      colorMatrix: [
        1.20,
        0.0,
        0.0,
        0.0,
        18.0,
        0.0,
        1.00,
        0.0,
        0.0,
        4.0,
        0.0,
        0.0,
        1.05,
        0.0,
        8.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'face_party_confetti',
      name: 'Party Confetti',
      category: EffectCategory.celebration,
      icon: Icons.celebration_rounded,
      previewColor: Color(0xFF8B5CF6),
      colorMatrix: [
        1.15,
        0.0,
        0.0,
        0.0,
        10.0,
        0.0,
        1.15,
        0.0,
        0.0,
        10.0,
        0.0,
        0.0,
        1.15,
        0.0,
        10.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'face_neon_crown',
      name: 'Cyber Crown',
      category: EffectCategory.faceAR,
      icon: Icons.military_tech_rounded,
      previewColor: Color(0xFFEAB308),
      isFaceTrackingRequired: true,
    ),
    const ChatyCameraEffect(
      id: 'face_comic_sketch',
      name: 'Comic Book',
      category: EffectCategory.cyber,
      icon: Icons.auto_stories_rounded,
      previewColor: Color(0xFFEF4444),
      colorMatrix: [
        1.4,
        0.0,
        0.0,
        0.0,
        -10.0,
        0.0,
        1.4,
        0.0,
        0.0,
        -10.0,
        0.0,
        0.0,
        1.4,
        0.0,
        -10.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
      ],
    ),
    const ChatyCameraEffect(
      id: 'face_pixel_retro',
      name: 'Pixel Arcade',
      category: EffectCategory.cyber,
      icon: Icons.videogame_asset_rounded,
      previewColor: Color(0xFF10B981),
    ),
    const ChatyCameraEffect(
      id: 'face_angel_halo',
      name: 'Angel Halo',
      category: EffectCategory.faceAR,
      icon: Icons.circle_outlined,
      previewColor: Color(0xFFFEF08A),
      isFaceTrackingRequired: true,
    ),
    const ChatyCameraEffect(
      id: 'face_sunglasses_aviator',
      name: 'Cool Shades',
      category: EffectCategory.faceAR,
      icon: Icons.visibility_rounded,
      previewColor: Color(0xFF0F172A),
      isFaceTrackingRequired: true,
    ),

    // --- BACKGROUND BLUR & VIRTUAL SCENES ---
    const ChatyCameraEffect(
      id: 'bg_portrait_blur',
      name: 'Studio Blur',
      category: EffectCategory.background,
      icon: Icons.blur_on_rounded,
      previewColor: Color(0xFF6366F1),
      isSegmentationRequired: true,
      tier: EffectPerformanceTier.gpuIntensive,
    ),
    const ChatyCameraEffect(
      id: 'bg_virtual_office',
      name: 'Modern Office',
      category: EffectCategory.background,
      icon: Icons.business_rounded,
      previewColor: Color(0xFF475569),
      isSegmentationRequired: true,
      tier: EffectPerformanceTier.gpuIntensive,
    ),
    const ChatyCameraEffect(
      id: 'bg_gradient_studio',
      name: 'Chaty Gradient',
      category: EffectCategory.background,
      icon: Icons.gradient_rounded,
      previewColor: Color(0xFF8B5CF6),
      isSegmentationRequired: true,
      tier: EffectPerformanceTier.gpuIntensive,
    ),
  ];

  /// Look up an effect by ID (falls back to Normal 'none')
  static ChatyCameraEffect getById(String id) {
    return allEffects.firstWhere(
      (e) => e.id == id,
      orElse: () => allEffects.first,
    );
  }

  /// Filter effects by category
  static List<ChatyCameraEffect> getByCategory(EffectCategory category) {
    return allEffects.where((e) => e.category == category).toList();
  }

  static final Map<String, ChatyCameraEffect> _byId = {
    for (final effect in allEffects) effect.id: effect,
  };

  /// Resolves a persisted effect id (message/story metadata). Unknown or
  /// missing ids degrade gracefully to the neutral effect.
  static ChatyCameraEffect byId(String? id) =>
      _byId[id?.trim() ?? ''] ?? allEffects.first;

  /// Wraps [child] in the color matrix of a stored effect so receivers see
  /// the same look the sender chose. Metadata keys: 'effect', optional
  /// 'effect_intensity' (0..1).
  static Widget applyStored(Widget child, Map<String, dynamic>? metadata) {
    final id = metadata?['effect']?.toString();
    if (id == null || id.isEmpty || id == 'none') return child;
    final effect = byId(id);
    if (effect.colorMatrix == null) return child;
    final intensity =
        (double.tryParse('${metadata?['effect_intensity'] ?? ''}') ??
                effect.defaultIntensity)
            .clamp(0.0, 1.0);
    const identity = <double>[
      1, 0, 0, 0, 0, //
      0, 1, 0, 0, 0, //
      0, 0, 1, 0, 0, //
      0, 0, 0, 1, 0,
    ];
    final matrix = <double>[
      for (var i = 0; i < 20; i++)
        identity[i] + (effect.colorMatrix![i] - identity[i]) * intensity,
    ];
    return ColorFiltered(colorFilter: ColorFilter.matrix(matrix), child: child);
  }
}
