import 'package:flutter/material.dart';
import 'theme_config.dart';
import '../bubbles/bubble_style_id.dart';
import '../ticks/delivery_icon_style.dart';

class ThemePresets {
  static const ThemeConfig monochromeDark = ThemeConfig(
    id: 'monochrome_dark',
    name: 'Monochrome Dark',
    brightness: Brightness.dark,
    accentColor: Color(0xFFFFFFFF),
    backgroundColor: Color(0xFF000000),
    surfaceColor: Color(0xFF121212),
    cardColor: Color(0xFF1C1C1E),
    primaryTextColor: Color(0xFFFFFFFF),
    secondaryTextColor: Color(0xFFA1A1AA),
    outgoingBubbleColor: Color(0xFF27272A),
    incomingBubbleColor: Color(0xFF18181B),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFFF4F4F5),
    linkColor: Color(0xFFE4E4E7),
    dangerColor: Color(0xFFEF4444),
    successColor: Color(0xFF10B981),
    cornerRadius: 16.0,
    density: 1.0,
    fontScale: 1.0,
    wallpaperId: 'none',
  );

  static const ThemeConfig monochromeLight = ThemeConfig(
    id: 'monochrome_light',
    name: 'Monochrome Light',
    brightness: Brightness.light,
    accentColor: Color(0xFF000000),
    backgroundColor: Color(0xFFFFFFFF),
    surfaceColor: Color(0xFFF4F4F5),
    cardColor: Color(0xFFFFFFFF),
    primaryTextColor: Color(0xFF09090B),
    secondaryTextColor: Color(0xFF71717A),
    outgoingBubbleColor: Color(0xFF09090B),
    incomingBubbleColor: Color(0xFFF4F4F5),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFF09090B),
    linkColor: Color(0xFF18181B),
    dangerColor: Color(0xFFDC2626),
    successColor: Color(0xFF059669),
    cornerRadius: 16.0,
    density: 1.0,
    fontScale: 1.0,
    wallpaperId: 'none',
  );

  static const ThemeConfig midnight = ThemeConfig(
    id: 'midnight',
    name: 'Midnight',
    brightness: Brightness.dark,
    accentColor: Color(0xFF6366F1),
    backgroundColor: Color(0xFF0B0F19),
    surfaceColor: Color(0xFF111827),
    cardColor: Color(0xFF1E293B),
    primaryTextColor: Color(0xFFF9FAFB),
    secondaryTextColor: Color(0xFF94A3B8),
    outgoingBubbleColor: Color(0xFF4F46E5),
    incomingBubbleColor: Color(0xFF1E293B),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFFF1F5F9),
    linkColor: Color(0xFF38BDF8),
    dangerColor: Color(0xFFEF4444),
    successColor: Color(0xFF10B981),
    cornerRadius: 16.0,
    density: 1.0,
    fontScale: 1.0,
    wallpaperId: 'subtle_dots',
  );

  static const ThemeConfig paper = ThemeConfig(
    id: 'paper',
    name: 'Paper',
    brightness: Brightness.light,
    accentColor: Color(0xFF0F172A),
    backgroundColor: Color(0xFFF8FAFC),
    surfaceColor: Color(0xFFFFFFFF),
    cardColor: Color(0xFFFFFFFF),
    primaryTextColor: Color(0xFF0F172A),
    secondaryTextColor: Color(0xFF64748B),
    outgoingBubbleColor: Color(0xFF0F172A),
    incomingBubbleColor: Color(0xFFE2E8F0),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFF0F172A),
    linkColor: Color(0xFF2563EB),
    dangerColor: Color(0xFFDC2626),
    successColor: Color(0xFF059669),
    cornerRadius: 14.0,
    density: 1.0,
    fontScale: 1.0,
    wallpaperId: 'none',
  );

  static const ThemeConfig ocean = ThemeConfig(
    id: 'ocean',
    name: 'Ocean',
    brightness: Brightness.dark,
    accentColor: Color(0xFF06B6D4),
    backgroundColor: Color(0xFF071A2E),
    surfaceColor: Color(0xFF0B2942),
    cardColor: Color(0xFF113857),
    primaryTextColor: Color(0xFFECFEFF),
    secondaryTextColor: Color(0xFF7DD3FC),
    outgoingBubbleColor: Color(0xFF0284C7),
    incomingBubbleColor: Color(0xFF0F3656),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFFE0F2FE),
    linkColor: Color(0xFF38BDF8),
    dangerColor: Color(0xFFF87171),
    successColor: Color(0xFF34D399),
    cornerRadius: 18.0,
    density: 1.0,
    fontScale: 1.0,
    wallpaperId: 'constellation',
  );

  static const ThemeConfig sunset = ThemeConfig(
    id: 'sunset',
    name: 'Sunset',
    brightness: Brightness.dark,
    accentColor: Color(0xFFF43F5E),
    backgroundColor: Color(0xFF1C1326),
    surfaceColor: Color(0xFF2B1C3A),
    cardColor: Color(0xFF3B274F),
    primaryTextColor: Color(0xFFFFF1F2),
    secondaryTextColor: Color(0xFFFDA4AF),
    outgoingBubbleColor: Color(0xFFE11D48),
    incomingBubbleColor: Color(0xFF38234C),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFFFFE4E6),
    linkColor: Color(0xFFFB923C),
    dangerColor: Color(0xFFEF4444),
    successColor: Color(0xFF10B981),
    cornerRadius: 20.0,
    density: 1.0,
    fontScale: 1.0,
    wallpaperId: 'gradient_mesh',
  );

  static const ThemeConfig forest = ThemeConfig(
    id: 'forest',
    name: 'Forest',
    brightness: Brightness.dark,
    accentColor: Color(0xFF10B981),
    backgroundColor: Color(0xFF091E15),
    surfaceColor: Color(0xFF0E2E20),
    cardColor: Color(0xFF15402D),
    primaryTextColor: Color(0xFFECFDF5),
    secondaryTextColor: Color(0xFF6EE7B7),
    outgoingBubbleColor: Color(0xFF059669),
    incomingBubbleColor: Color(0xFF163E2C),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFFD1FAE5),
    linkColor: Color(0xFF34D399),
    dangerColor: Color(0xFFF87171),
    successColor: Color(0xFF10B981),
    cornerRadius: 16.0,
    density: 1.0,
    fontScale: 1.0,
    wallpaperId: 'geometric',
  );

  static const ThemeConfig highContrast = ThemeConfig(
    id: 'high_contrast',
    name: 'High Contrast',
    brightness: Brightness.dark,
    accentColor: Color(0xFFFFFF00),
    backgroundColor: Color(0xFF000000),
    surfaceColor: Color(0xFF121212),
    cardColor: Color(0xFF1E1E1E),
    primaryTextColor: Color(0xFFFFFFFF),
    secondaryTextColor: Color(0xFFCCCCCC),
    outgoingBubbleColor: Color(0xFFFFFF00),
    incomingBubbleColor: Color(0xFF262626),
    outgoingTextColor: Color(0xFF000000),
    incomingTextColor: Color(0xFFFFFFFF),
    linkColor: Color(0xFF00E5FF),
    dangerColor: Color(0xFFFF5252),
    successColor: Color(0xFF00E676),
    cornerRadius: 8.0,
    density: 1.1,
    fontScale: 1.1,
    highContrast: true,
    wallpaperId: 'none',
  );

  static const ThemeConfig graphite = ThemeConfig(
    id: 'graphite',
    name: 'Graphite',
    brightness: Brightness.dark,
    accentColor: Color(0xFF94A3B8),
    backgroundColor: Color(0xFF121212),
    surfaceColor: Color(0xFF1E1E1E),
    cardColor: Color(0xFF2B2B2B),
    primaryTextColor: Color(0xFFF8FAFC),
    secondaryTextColor: Color(0xFF94A3B8),
    outgoingBubbleColor: Color(0xFF334155),
    incomingBubbleColor: Color(0xFF1E293B),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFFF1F5F9),
    linkColor: Color(0xFF60A5FA),
    dangerColor: Color(0xFFF87171),
    successColor: Color(0xFF4ADE80),
    cornerRadius: 12.0,
  );

  static const ThemeConfig lavender = ThemeConfig(
    id: 'lavender',
    name: 'Lavender',
    brightness: Brightness.light,
    accentColor: Color(0xFF8B5CF6),
    backgroundColor: Color(0xFFF5F3FF),
    surfaceColor: Color(0xFFFFFFFF),
    cardColor: Color(0xFFEDE9FE),
    primaryTextColor: Color(0xFF4C1D95),
    secondaryTextColor: Color(0xFF6D28D9),
    outgoingBubbleColor: Color(0xFF7C3AED),
    incomingBubbleColor: Color(0xFFDDD6FE),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFF4C1D95),
    linkColor: Color(0xFF6D28D9),
    dangerColor: Color(0xFFEF4444),
    successColor: Color(0xFF10B981),
    cornerRadius: 18.0,
  );

  static const ThemeConfig rose = ThemeConfig(
    id: 'rose',
    name: 'Rose',
    brightness: Brightness.light,
    accentColor: Color(0xFFF43F5E),
    backgroundColor: Color(0xFFFFF1F2),
    surfaceColor: Color(0xFFFFFFFF),
    cardColor: Color(0xFFFFE4E6),
    primaryTextColor: Color(0xFF881337),
    secondaryTextColor: Color(0xFF9F1239),
    outgoingBubbleColor: Color(0xFFE11D48),
    incomingBubbleColor: Color(0xFFFECDD3),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFF881337),
    linkColor: Color(0xFFE11D48),
    dangerColor: Color(0xFFE11D48),
    successColor: Color(0xFF10B981),
    cornerRadius: 18.0,
  );

  static const ThemeConfig coffee = ThemeConfig(
    id: 'coffee',
    name: 'Coffee',
    brightness: Brightness.dark,
    accentColor: Color(0xFFD97706),
    backgroundColor: Color(0xFF1C1917),
    surfaceColor: Color(0xFF292524),
    cardColor: Color(0xFF44403C),
    primaryTextColor: Color(0xFFFAFAF9),
    secondaryTextColor: Color(0xFFA8A29E),
    outgoingBubbleColor: Color(0xFFB45309),
    incomingBubbleColor: Color(0xFF292524),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFFF5F5F4),
    linkColor: Color(0xFFF59E0B),
    dangerColor: Color(0xFFEF4444),
    successColor: Color(0xFF10B981),
    cornerRadius: 16.0,
  );

  static const ThemeConfig arctic = ThemeConfig(
    id: 'arctic',
    name: 'Arctic',
    brightness: Brightness.light,
    accentColor: Color(0xFF0284C7),
    backgroundColor: Color(0xFFF0F9FF),
    surfaceColor: Color(0xFFFFFFFF),
    cardColor: Color(0xFFE0F2FE),
    primaryTextColor: Color(0xFF0C4A6E),
    secondaryTextColor: Color(0xFF0369A1),
    outgoingBubbleColor: Color(0xFF0284C7),
    incomingBubbleColor: Color(0xFFBAE6FD),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFF0C4A6E),
    linkColor: Color(0xFF0284C7),
    dangerColor: Color(0xFFEF4444),
    successColor: Color(0xFF10B981),
    cornerRadius: 16.0,
  );

  static const ThemeConfig amoled = ThemeConfig(
    id: 'amoled',
    name: 'AMOLED',
    brightness: Brightness.dark,
    accentColor: Color(0xFF38BDF8),
    backgroundColor: Color(0xFF000000),
    surfaceColor: Color(0xFF0A0A0A),
    cardColor: Color(0xFF141414),
    primaryTextColor: Color(0xFFFFFFFF),
    secondaryTextColor: Color(0xFFA3A3A3),
    outgoingBubbleColor: Color(0xFF0284C7),
    incomingBubbleColor: Color(0xFF171717),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFFFAFAFA),
    linkColor: Color(0xFF38BDF8),
    dangerColor: Color(0xFFEF4444),
    successColor: Color(0xFF22C55E),
    cornerRadius: 14.0,
  );

  static const ThemeConfig warmNeutral = ThemeConfig(
    id: 'warm_neutral',
    name: 'Warm Neutral',
    brightness: Brightness.light,
    accentColor: Color(0xFF8C5E3C),
    backgroundColor: Color(0xFFF7F5F0),
    surfaceColor: Color(0xFFFFFFFF),
    cardColor: Color(0xFFEDE8DF),
    primaryTextColor: Color(0xFF2B2623),
    secondaryTextColor: Color(0xFF7D756D),
    outgoingBubbleColor: Color(0xFF8C5E3C),
    incomingBubbleColor: Color(0xFFEDE8DF),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFF2B2623),
    linkColor: Color(0xFF9A5B32),
    dangerColor: Color(0xFFDC2626),
    successColor: Color(0xFF16A34A),
    cornerRadius: 16.0,
  );

  static const ThemeConfig warmNeutralDark = ThemeConfig(
    id: 'warm_neutral_dark',
    name: 'Warm Neutral Dark',
    brightness: Brightness.dark,
    accentColor: Color(0xFFD4A373),
    backgroundColor: Color(0xFF1C1917),
    surfaceColor: Color(0xFF292524),
    cardColor: Color(0xFF383330),
    primaryTextColor: Color(0xFFFAF7F2),
    secondaryTextColor: Color(0xFFA8A29E),
    outgoingBubbleColor: Color(0xFF8C5E3C),
    incomingBubbleColor: Color(0xFF292524),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFFFAF7F2),
    linkColor: Color(0xFFE6AD7A),
    dangerColor: Color(0xFFEF4444),
    successColor: Color(0xFF22C55E),
    cornerRadius: 16.0,
  );

  static const ThemeConfig cobalt = ThemeConfig(
    id: 'cobalt',
    name: 'Cobalt',
    brightness: Brightness.dark,
    accentColor: Color(0xFF60A5FA),
    backgroundColor: Color(0xFF07111F),
    surfaceColor: Color(0xFF0D1D33),
    cardColor: Color(0xFF142A47),
    primaryTextColor: Color(0xFFF8FBFF),
    secondaryTextColor: Color(0xFF9CC5F1),
    outgoingBubbleColor: Color(0xFF2563EB),
    incomingBubbleColor: Color(0xFF17304F),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFFF3F8FF),
    linkColor: Color(0xFF93C5FD),
    dangerColor: Color(0xFFF87171),
    successColor: Color(0xFF34D399),
    cornerRadius: 17.0,
  );

  static const ThemeConfig sage = ThemeConfig(
    id: 'sage',
    name: 'Sage',
    brightness: Brightness.light,
    accentColor: Color(0xFF3F6550),
    backgroundColor: Color(0xFFF4F7F2),
    surfaceColor: Color(0xFFFFFFFF),
    cardColor: Color(0xFFE6EEE8),
    primaryTextColor: Color(0xFF173326),
    secondaryTextColor: Color(0xFF52695C),
    outgoingBubbleColor: Color(0xFF3F6550),
    incomingBubbleColor: Color(0xFFDCE8DF),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFF173326),
    linkColor: Color(0xFF2E6B4A),
    dangerColor: Color(0xFFB42318),
    successColor: Color(0xFF287A4B),
    cornerRadius: 18.0,
  );

  static const ThemeConfig burgundy = ThemeConfig(
    id: 'burgundy',
    name: 'Burgundy',
    brightness: Brightness.dark,
    accentColor: Color(0xFFFB7185),
    backgroundColor: Color(0xFF1A0B10),
    surfaceColor: Color(0xFF291119),
    cardColor: Color(0xFF3B1923),
    primaryTextColor: Color(0xFFFFF7F8),
    secondaryTextColor: Color(0xFFE8A1AE),
    outgoingBubbleColor: Color(0xFF9F1239),
    incomingBubbleColor: Color(0xFF3A1721),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFFFFF1F3),
    linkColor: Color(0xFFFDA4AF),
    dangerColor: Color(0xFFFF6B6B),
    successColor: Color(0xFF4ADE80),
    cornerRadius: 18.0,
  );

  static const ThemeConfig daylight = ThemeConfig(
    id: 'daylight',
    name: 'Daylight',
    brightness: Brightness.light,
    accentColor: Color(0xFF1D4ED8),
    backgroundColor: Color(0xFFFFFEFA),
    surfaceColor: Color(0xFFFFFFFF),
    cardColor: Color(0xFFF1F5F9),
    primaryTextColor: Color(0xFF111827),
    secondaryTextColor: Color(0xFF586174),
    outgoingBubbleColor: Color(0xFF1D4ED8),
    incomingBubbleColor: Color(0xFFE8EEF7),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFF111827),
    linkColor: Color(0xFF1D4ED8),
    dangerColor: Color(0xFFB91C1C),
    successColor: Color(0xFF15803D),
    cornerRadius: 14.0,
  );

  static const ThemeConfig violetNight = ThemeConfig(
    id: 'violet_night',
    name: 'Violet Night',
    brightness: Brightness.dark,
    accentColor: Color(0xFFA78BFA),
    backgroundColor: Color(0xFF100D1A),
    surfaceColor: Color(0xFF191428),
    cardColor: Color(0xFF28203E),
    primaryTextColor: Color(0xFFF8F5FF),
    secondaryTextColor: Color(0xFFC4B5FD),
    outgoingBubbleColor: Color(0xFF7C3AED),
    incomingBubbleColor: Color(0xFF2A2141),
    outgoingTextColor: Color(0xFFFFFFFF),
    incomingTextColor: Color(0xFFF5F3FF),
    linkColor: Color(0xFFC4B5FD),
    dangerColor: Color(0xFFFB7185),
    successColor: Color(0xFF34D399),
    cornerRadius: 20.0,
  );

  /// WhatsApp iOS (light) — the app's default identity. Authentic palette:
  /// white list chrome, #D9FDD3 outgoing bubbles, #111B21 ink, #667781 gray,
  /// #25D366 green accents, tail-less 18px bubbles, plain background.
  static const whatsappIosLight = ThemeConfig(
    id: 'whatsapp_ios_light',
    name: 'WhatsApp iOS',
    brightness: Brightness.light,
    accentColor: Color(0xFF25D366),
    backgroundColor: Color(0xFFFFFFFF),
    surfaceColor: Color(0xFFFFFFFF),
    cardColor: Color(0xFFF6F6F6),
    primaryTextColor: Color(0xFF111B21),
    secondaryTextColor: Color(0xFF667781),
    outgoingBubbleColor: Color(0xFFD9FDD3),
    incomingBubbleColor: Color(0xFFFFFFFF),
    outgoingTextColor: Color(0xFF111B21),
    incomingTextColor: Color(0xFF111B21),
    linkColor: Color(0xFF027EB5),
    dangerColor: Color(0xFFEA4335),
    successColor: Color(0xFF25D366),
    cornerRadius: 14.0,
    density: 1.0,
    fontScale: 1.0,
    bubbleStyle: BubbleStyleId.rcIos11,
    deliveryTickStyle: DeliveryIconStyle.rcIos11,
    wallpaperId: 'none',
  );

  /// WhatsApp iOS (dark) — #0B141A canvas, #111B21 chrome, #202C33 panels,
  /// #005C4B outgoing bubbles, #53BDEB links/ticks.
  static const whatsappIosDark = ThemeConfig(
    id: 'whatsapp_ios_dark',
    name: 'WhatsApp iOS Dark',
    brightness: Brightness.dark,
    accentColor: Color(0xFF21C063),
    backgroundColor: Color(0xFF0B141A),
    surfaceColor: Color(0xFF111B21),
    cardColor: Color(0xFF202C33),
    primaryTextColor: Color(0xFFE9EDEF),
    secondaryTextColor: Color(0xFF8696A0),
    outgoingBubbleColor: Color(0xFF005C4B),
    incomingBubbleColor: Color(0xFF202C33),
    outgoingTextColor: Color(0xFFE9EDEF),
    incomingTextColor: Color(0xFFE9EDEF),
    linkColor: Color(0xFF53BDEB),
    dangerColor: Color(0xFFEF4444),
    successColor: Color(0xFF21C063),
    cornerRadius: 14.0,
    density: 1.0,
    fontScale: 1.0,
    bubbleStyle: BubbleStyleId.rcIos11,
    deliveryTickStyle: DeliveryIconStyle.rcIos11,
    wallpaperId: 'none',
  );

  static const List<ThemeConfig> all = <ThemeConfig>[
    whatsappIosLight,
    whatsappIosDark,
    monochromeDark,
    monochromeLight,
    midnight,
    paper,
    ocean,
    sunset,
    forest,
    highContrast,
    graphite,
    lavender,
    rose,
    coffee,
    arctic,
    amoled,
    warmNeutral,
    warmNeutralDark,
    cobalt,
    sage,
    burgundy,
    daylight,
    violetNight,
  ];

  static ThemeConfig getSystemDefaultTheme([Brightness? platformBrightness]) {
    final brightness =
        platformBrightness ??
        WidgetsBinding.instance.platformDispatcher.platformBrightness;
    return brightness == Brightness.light ? warmNeutral : warmNeutralDark;
  }

  static ThemeConfig getById(String id) {
    return all.firstWhere(
      (theme) => theme.id == id,
      orElse: () => monochromeDark,
    );
  }
}
